// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/license/certificate.proto

package license

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Certificate service

func NewCertificateEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Certificate service

type CertificateService interface {
	// 获取
	Get(ctx context.Context, in *CerGetRequest, opts ...client.CallOption) (*CerGetResponse, error)
	// 列举
	List(ctx context.Context, in *CerListRequest, opts ...client.CallOption) (*CerListResponse, error)
	// 搜索
	Search(ctx context.Context, in *CerSearchRequest, opts ...client.CallOption) (*CerListResponse, error)
}

type certificateService struct {
	c    client.Client
	name string
}

func NewCertificateService(name string, c client.Client) CertificateService {
	return &certificateService{
		c:    c,
		name: name,
	}
}

func (c *certificateService) Get(ctx context.Context, in *CerGetRequest, opts ...client.CallOption) (*CerGetResponse, error) {
	req := c.c.NewRequest(c.name, "Certificate.Get", in)
	out := new(CerGetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateService) List(ctx context.Context, in *CerListRequest, opts ...client.CallOption) (*CerListResponse, error) {
	req := c.c.NewRequest(c.name, "Certificate.List", in)
	out := new(CerListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateService) Search(ctx context.Context, in *CerSearchRequest, opts ...client.CallOption) (*CerListResponse, error) {
	req := c.c.NewRequest(c.name, "Certificate.Search", in)
	out := new(CerListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Certificate service

type CertificateHandler interface {
	// 获取
	Get(context.Context, *CerGetRequest, *CerGetResponse) error
	// 列举
	List(context.Context, *CerListRequest, *CerListResponse) error
	// 搜索
	Search(context.Context, *CerSearchRequest, *CerListResponse) error
}

func RegisterCertificateHandler(s server.Server, hdlr CertificateHandler, opts ...server.HandlerOption) error {
	type certificate interface {
		Get(ctx context.Context, in *CerGetRequest, out *CerGetResponse) error
		List(ctx context.Context, in *CerListRequest, out *CerListResponse) error
		Search(ctx context.Context, in *CerSearchRequest, out *CerListResponse) error
	}
	type Certificate struct {
		certificate
	}
	h := &certificateHandler{hdlr}
	return s.Handle(s.NewHandler(&Certificate{h}, opts...))
}

type certificateHandler struct {
	CertificateHandler
}

func (h *certificateHandler) Get(ctx context.Context, in *CerGetRequest, out *CerGetResponse) error {
	return h.CertificateHandler.Get(ctx, in, out)
}

func (h *certificateHandler) List(ctx context.Context, in *CerListRequest, out *CerListResponse) error {
	return h.CertificateHandler.List(ctx, in, out)
}

func (h *certificateHandler) Search(ctx context.Context, in *CerSearchRequest, out *CerListResponse) error {
	return h.CertificateHandler.Search(ctx, in, out)
}
