// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/license/certificate.proto

package license

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 获取的请求
type CerFetchRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CerFetchRequest) Reset()         { *m = CerFetchRequest{} }
func (m *CerFetchRequest) String() string { return proto.CompactTextString(m) }
func (*CerFetchRequest) ProtoMessage()    {}
func (*CerFetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45a2be42a86bdaa, []int{0}
}

func (m *CerFetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CerFetchRequest.Unmarshal(m, b)
}
func (m *CerFetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CerFetchRequest.Marshal(b, m, deterministic)
}
func (m *CerFetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CerFetchRequest.Merge(m, src)
}
func (m *CerFetchRequest) XXX_Size() int {
	return xxx_messageInfo_CerFetchRequest.Size(m)
}
func (m *CerFetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CerFetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CerFetchRequest proto.InternalMessageInfo

func (m *CerFetchRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

// 获取的回复
type CerFetchResponse struct {
	Status               *Status            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Cer                  *CertificateEntity `protobuf:"bytes,2,opt,name=cer,proto3" json:"cer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CerFetchResponse) Reset()         { *m = CerFetchResponse{} }
func (m *CerFetchResponse) String() string { return proto.CompactTextString(m) }
func (*CerFetchResponse) ProtoMessage()    {}
func (*CerFetchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45a2be42a86bdaa, []int{1}
}

func (m *CerFetchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CerFetchResponse.Unmarshal(m, b)
}
func (m *CerFetchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CerFetchResponse.Marshal(b, m, deterministic)
}
func (m *CerFetchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CerFetchResponse.Merge(m, src)
}
func (m *CerFetchResponse) XXX_Size() int {
	return xxx_messageInfo_CerFetchResponse.Size(m)
}
func (m *CerFetchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CerFetchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CerFetchResponse proto.InternalMessageInfo

func (m *CerFetchResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CerFetchResponse) GetCer() *CertificateEntity {
	if m != nil {
		return m.Cer
	}
	return nil
}

// 列举的请求
type CerListRequest struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Space                string   `protobuf:"bytes,3,opt,name=space,proto3" json:"space,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CerListRequest) Reset()         { *m = CerListRequest{} }
func (m *CerListRequest) String() string { return proto.CompactTextString(m) }
func (*CerListRequest) ProtoMessage()    {}
func (*CerListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45a2be42a86bdaa, []int{2}
}

func (m *CerListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CerListRequest.Unmarshal(m, b)
}
func (m *CerListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CerListRequest.Marshal(b, m, deterministic)
}
func (m *CerListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CerListRequest.Merge(m, src)
}
func (m *CerListRequest) XXX_Size() int {
	return xxx_messageInfo_CerListRequest.Size(m)
}
func (m *CerListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CerListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CerListRequest proto.InternalMessageInfo

func (m *CerListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *CerListRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *CerListRequest) GetSpace() string {
	if m != nil {
		return m.Space
	}
	return ""
}

// 列举的回复
type CerListResponse struct {
	Status               *Status              `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64                `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Cer                  []*CertificateEntity `protobuf:"bytes,3,rep,name=cer,proto3" json:"cer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CerListResponse) Reset()         { *m = CerListResponse{} }
func (m *CerListResponse) String() string { return proto.CompactTextString(m) }
func (*CerListResponse) ProtoMessage()    {}
func (*CerListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45a2be42a86bdaa, []int{3}
}

func (m *CerListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CerListResponse.Unmarshal(m, b)
}
func (m *CerListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CerListResponse.Marshal(b, m, deterministic)
}
func (m *CerListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CerListResponse.Merge(m, src)
}
func (m *CerListResponse) XXX_Size() int {
	return xxx_messageInfo_CerListResponse.Size(m)
}
func (m *CerListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CerListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CerListResponse proto.InternalMessageInfo

func (m *CerListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CerListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CerListResponse) GetCer() []*CertificateEntity {
	if m != nil {
		return m.Cer
	}
	return nil
}

func init() {
	proto.RegisterType((*CerFetchRequest)(nil), "license.CerFetchRequest")
	proto.RegisterType((*CerFetchResponse)(nil), "license.CerFetchResponse")
	proto.RegisterType((*CerListRequest)(nil), "license.CerListRequest")
	proto.RegisterType((*CerListResponse)(nil), "license.CerListResponse")
}

func init() {
	proto.RegisterFile("proto/license/certificate.proto", fileDescriptor_a45a2be42a86bdaa)
}

var fileDescriptor_a45a2be42a86bdaa = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x29, 0x26, 0x45, 0x5c, 0x25, 0x5a, 0x59, 0x15, 0x84, 0x2c, 0x54, 0x61, 0x80, 0x01,
	0xa5, 0x52, 0x19, 0x91, 0x58, 0x22, 0x98, 0x98, 0x0c, 0x7f, 0x20, 0xb8, 0x17, 0xd5, 0x52, 0x15,
	0x07, 0xfb, 0x32, 0xb0, 0xf0, 0x03, 0xf8, 0xd5, 0x28, 0xe7, 0x84, 0x06, 0xc1, 0x00, 0x9b, 0x9f,
	0xdf, 0xe7, 0xf3, 0x7b, 0x36, 0x9c, 0xd7, 0xce, 0x92, 0x5d, 0x6e, 0x8d, 0xc6, 0xca, 0xe3, 0x52,
	0xa3, 0x23, 0x53, 0x1a, 0x5d, 0x10, 0x66, 0xec, 0xc8, 0xc3, 0xce, 0x4a, 0x92, 0xef, 0xa4, 0xdf,
	0x14, 0x0e, 0xd7, 0x01, 0x4a, 0x2f, 0x60, 0x9a, 0xa3, 0x7b, 0x40, 0xd2, 0x1b, 0x85, 0xaf, 0x0d,
	0x7a, 0x92, 0x33, 0x10, 0x8d, 0x59, 0xc7, 0xa3, 0xc5, 0xe8, 0xea, 0x48, 0xb5, 0xcb, 0xd4, 0xc0,
	0x6c, 0x07, 0xf9, 0xda, 0x56, 0x1e, 0xe5, 0x25, 0x8c, 0x3d, 0x15, 0xd4, 0x78, 0x06, 0x27, 0xab,
	0x69, 0xd6, 0xcd, 0xcf, 0x9e, 0x78, 0x5b, 0x75, 0xb6, 0xbc, 0x06, 0xa1, 0xd1, 0xc5, 0xfb, 0x4c,
	0x25, 0x5f, 0x54, 0xbe, 0xcb, 0x7b, 0x5f, 0x91, 0xa1, 0x37, 0xd5, 0x62, 0xe9, 0x33, 0x1c, 0xe7,
	0xe8, 0x1e, 0x8d, 0xa7, 0x3e, 0xce, 0x09, 0x8c, 0x6d, 0x59, 0x7a, 0x24, 0xbe, 0x28, 0x52, 0x9d,
	0x92, 0x73, 0x88, 0xb4, 0x6d, 0x2a, 0xe2, 0xc9, 0x91, 0x0a, 0xa2, 0xdd, 0xf5, 0x75, 0xa1, 0x31,
	0x16, 0x1c, 0x3f, 0x88, 0xf4, 0x9d, 0x5b, 0x86, 0xa9, 0xff, 0xcd, 0x3f, 0x87, 0x88, 0x2c, 0x15,
	0x5b, 0xbe, 0x47, 0xa8, 0x20, 0xfa, 0x56, 0x62, 0x21, 0xfe, 0xd0, 0x6a, 0xf5, 0x31, 0x82, 0xc9,
	0xc0, 0x92, 0x77, 0x10, 0xf1, 0x6b, 0xca, 0x78, 0x78, 0x72, 0xf8, 0x0b, 0xc9, 0xd9, 0x2f, 0x4e,
	0x88, 0x9e, 0xee, 0xc9, 0x5b, 0x38, 0x68, 0xcb, 0xc8, 0xd3, 0x21, 0x34, 0x78, 0xb4, 0x24, 0xfe,
	0x69, 0xf4, 0x87, 0x5f, 0xc6, 0xfc, 0xf3, 0x37, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x64,
	0x18, 0xa2, 0x41, 0x02, 0x00, 0x00,
}
