// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/license/key.proto

package license

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 生成的请求
type KeyGenerateRequest struct {
	SpaceKey             string   `protobuf:"bytes,1,opt,name=spaceKey,proto3" json:"spaceKey,omitempty"`
	SpaceSecret          string   `protobuf:"bytes,2,opt,name=spaceSecret,proto3" json:"spaceSecret,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Capacity             int32    `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Expiry               int32    `protobuf:"varint,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Storage              string   `protobuf:"bytes,6,opt,name=storage,proto3" json:"storage,omitempty"`
	Profile              string   `protobuf:"bytes,7,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyGenerateRequest) Reset()         { *m = KeyGenerateRequest{} }
func (m *KeyGenerateRequest) String() string { return proto.CompactTextString(m) }
func (*KeyGenerateRequest) ProtoMessage()    {}
func (*KeyGenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{0}
}

func (m *KeyGenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyGenerateRequest.Unmarshal(m, b)
}
func (m *KeyGenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyGenerateRequest.Marshal(b, m, deterministic)
}
func (m *KeyGenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyGenerateRequest.Merge(m, src)
}
func (m *KeyGenerateRequest) XXX_Size() int {
	return xxx_messageInfo_KeyGenerateRequest.Size(m)
}
func (m *KeyGenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyGenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyGenerateRequest proto.InternalMessageInfo

func (m *KeyGenerateRequest) GetSpaceKey() string {
	if m != nil {
		return m.SpaceKey
	}
	return ""
}

func (m *KeyGenerateRequest) GetSpaceSecret() string {
	if m != nil {
		return m.SpaceSecret
	}
	return ""
}

func (m *KeyGenerateRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *KeyGenerateRequest) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *KeyGenerateRequest) GetExpiry() int32 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *KeyGenerateRequest) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *KeyGenerateRequest) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

// 生成的回复
type KeyGenerateResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Number               []string `protobuf:"bytes,2,rep,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyGenerateResponse) Reset()         { *m = KeyGenerateResponse{} }
func (m *KeyGenerateResponse) String() string { return proto.CompactTextString(m) }
func (*KeyGenerateResponse) ProtoMessage()    {}
func (*KeyGenerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{1}
}

func (m *KeyGenerateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyGenerateResponse.Unmarshal(m, b)
}
func (m *KeyGenerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyGenerateResponse.Marshal(b, m, deterministic)
}
func (m *KeyGenerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyGenerateResponse.Merge(m, src)
}
func (m *KeyGenerateResponse) XXX_Size() int {
	return xxx_messageInfo_KeyGenerateResponse.Size(m)
}
func (m *KeyGenerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyGenerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyGenerateResponse proto.InternalMessageInfo

func (m *KeyGenerateResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *KeyGenerateResponse) GetNumber() []string {
	if m != nil {
		return m.Number
	}
	return nil
}

// 查询的请求
type KeyQueryRequest struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyQueryRequest) Reset()         { *m = KeyQueryRequest{} }
func (m *KeyQueryRequest) String() string { return proto.CompactTextString(m) }
func (*KeyQueryRequest) ProtoMessage()    {}
func (*KeyQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{2}
}

func (m *KeyQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyQueryRequest.Unmarshal(m, b)
}
func (m *KeyQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyQueryRequest.Marshal(b, m, deterministic)
}
func (m *KeyQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyQueryRequest.Merge(m, src)
}
func (m *KeyQueryRequest) XXX_Size() int {
	return xxx_messageInfo_KeyQueryRequest.Size(m)
}
func (m *KeyQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyQueryRequest proto.InternalMessageInfo

func (m *KeyQueryRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

// 查询的回复
type KeyQueryResponse struct {
	Status               *Status    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Key                  *KeyEntity `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *KeyQueryResponse) Reset()         { *m = KeyQueryResponse{} }
func (m *KeyQueryResponse) String() string { return proto.CompactTextString(m) }
func (*KeyQueryResponse) ProtoMessage()    {}
func (*KeyQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{3}
}

func (m *KeyQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyQueryResponse.Unmarshal(m, b)
}
func (m *KeyQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyQueryResponse.Marshal(b, m, deterministic)
}
func (m *KeyQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyQueryResponse.Merge(m, src)
}
func (m *KeyQueryResponse) XXX_Size() int {
	return xxx_messageInfo_KeyQueryResponse.Size(m)
}
func (m *KeyQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyQueryResponse proto.InternalMessageInfo

func (m *KeyQueryResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *KeyQueryResponse) GetKey() *KeyEntity {
	if m != nil {
		return m.Key
	}
	return nil
}

// 激活的请求
type KeyActivateRequest struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Consumer             string   `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Space                string   `protobuf:"bytes,3,opt,name=space,proto3" json:"space,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyActivateRequest) Reset()         { *m = KeyActivateRequest{} }
func (m *KeyActivateRequest) String() string { return proto.CompactTextString(m) }
func (*KeyActivateRequest) ProtoMessage()    {}
func (*KeyActivateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{4}
}

func (m *KeyActivateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyActivateRequest.Unmarshal(m, b)
}
func (m *KeyActivateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyActivateRequest.Marshal(b, m, deterministic)
}
func (m *KeyActivateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyActivateRequest.Merge(m, src)
}
func (m *KeyActivateRequest) XXX_Size() int {
	return xxx_messageInfo_KeyActivateRequest.Size(m)
}
func (m *KeyActivateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyActivateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyActivateRequest proto.InternalMessageInfo

func (m *KeyActivateRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *KeyActivateRequest) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *KeyActivateRequest) GetSpace() string {
	if m != nil {
		return m.Space
	}
	return ""
}

// 激活的回复
type KeyActivateResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CerUID               string   `protobuf:"bytes,2,opt,name=cerUID,proto3" json:"cerUID,omitempty"`
	CerContent           string   `protobuf:"bytes,3,opt,name=cerContent,proto3" json:"cerContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyActivateResponse) Reset()         { *m = KeyActivateResponse{} }
func (m *KeyActivateResponse) String() string { return proto.CompactTextString(m) }
func (*KeyActivateResponse) ProtoMessage()    {}
func (*KeyActivateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{5}
}

func (m *KeyActivateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyActivateResponse.Unmarshal(m, b)
}
func (m *KeyActivateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyActivateResponse.Marshal(b, m, deterministic)
}
func (m *KeyActivateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyActivateResponse.Merge(m, src)
}
func (m *KeyActivateResponse) XXX_Size() int {
	return xxx_messageInfo_KeyActivateResponse.Size(m)
}
func (m *KeyActivateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyActivateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyActivateResponse proto.InternalMessageInfo

func (m *KeyActivateResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *KeyActivateResponse) GetCerUID() string {
	if m != nil {
		return m.CerUID
	}
	return ""
}

func (m *KeyActivateResponse) GetCerContent() string {
	if m != nil {
		return m.CerContent
	}
	return ""
}

// 挂起的请求
type KeySuspendRequest struct {
	SpaceKey             string   `protobuf:"bytes,1,opt,name=spaceKey,proto3" json:"spaceKey,omitempty"`
	SpaceSecret          string   `protobuf:"bytes,2,opt,name=spaceSecret,proto3" json:"spaceSecret,omitempty"`
	Number               string   `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	Ban                  int32    `protobuf:"varint,4,opt,name=ban,proto3" json:"ban,omitempty"`
	Reason               string   `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeySuspendRequest) Reset()         { *m = KeySuspendRequest{} }
func (m *KeySuspendRequest) String() string { return proto.CompactTextString(m) }
func (*KeySuspendRequest) ProtoMessage()    {}
func (*KeySuspendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{6}
}

func (m *KeySuspendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeySuspendRequest.Unmarshal(m, b)
}
func (m *KeySuspendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeySuspendRequest.Marshal(b, m, deterministic)
}
func (m *KeySuspendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeySuspendRequest.Merge(m, src)
}
func (m *KeySuspendRequest) XXX_Size() int {
	return xxx_messageInfo_KeySuspendRequest.Size(m)
}
func (m *KeySuspendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeySuspendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeySuspendRequest proto.InternalMessageInfo

func (m *KeySuspendRequest) GetSpaceKey() string {
	if m != nil {
		return m.SpaceKey
	}
	return ""
}

func (m *KeySuspendRequest) GetSpaceSecret() string {
	if m != nil {
		return m.SpaceSecret
	}
	return ""
}

func (m *KeySuspendRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *KeySuspendRequest) GetBan() int32 {
	if m != nil {
		return m.Ban
	}
	return 0
}

func (m *KeySuspendRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// 列举的请求
type KeyListRequest struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyListRequest) Reset()         { *m = KeyListRequest{} }
func (m *KeyListRequest) String() string { return proto.CompactTextString(m) }
func (*KeyListRequest) ProtoMessage()    {}
func (*KeyListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{7}
}

func (m *KeyListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyListRequest.Unmarshal(m, b)
}
func (m *KeyListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyListRequest.Marshal(b, m, deterministic)
}
func (m *KeyListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyListRequest.Merge(m, src)
}
func (m *KeyListRequest) XXX_Size() int {
	return xxx_messageInfo_KeyListRequest.Size(m)
}
func (m *KeyListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyListRequest proto.InternalMessageInfo

func (m *KeyListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *KeyListRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 列举的回复
type KeyListResponse struct {
	Status               *Status      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Key                  []*KeyEntity `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *KeyListResponse) Reset()         { *m = KeyListResponse{} }
func (m *KeyListResponse) String() string { return proto.CompactTextString(m) }
func (*KeyListResponse) ProtoMessage()    {}
func (*KeyListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{8}
}

func (m *KeyListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyListResponse.Unmarshal(m, b)
}
func (m *KeyListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyListResponse.Marshal(b, m, deterministic)
}
func (m *KeyListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyListResponse.Merge(m, src)
}
func (m *KeyListResponse) XXX_Size() int {
	return xxx_messageInfo_KeyListResponse.Size(m)
}
func (m *KeyListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyListResponse proto.InternalMessageInfo

func (m *KeyListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *KeyListResponse) GetKey() []*KeyEntity {
	if m != nil {
		return m.Key
	}
	return nil
}

func init() {
	proto.RegisterType((*KeyGenerateRequest)(nil), "license.KeyGenerateRequest")
	proto.RegisterType((*KeyGenerateResponse)(nil), "license.KeyGenerateResponse")
	proto.RegisterType((*KeyQueryRequest)(nil), "license.KeyQueryRequest")
	proto.RegisterType((*KeyQueryResponse)(nil), "license.KeyQueryResponse")
	proto.RegisterType((*KeyActivateRequest)(nil), "license.KeyActivateRequest")
	proto.RegisterType((*KeyActivateResponse)(nil), "license.KeyActivateResponse")
	proto.RegisterType((*KeySuspendRequest)(nil), "license.KeySuspendRequest")
	proto.RegisterType((*KeyListRequest)(nil), "license.KeyListRequest")
	proto.RegisterType((*KeyListResponse)(nil), "license.KeyListResponse")
}

func init() {
	proto.RegisterFile("proto/license/key.proto", fileDescriptor_1b5dda835d30aee6)
}

var fileDescriptor_1b5dda835d30aee6 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0x5d, 0x9b, 0xb5, 0x5d, 0xef, 0xa4, 0xdf, 0xf6, 0x33, 0x68, 0x33, 0x01, 0xa1, 0x2a, 0x42,
	0xa2, 0xbc, 0x74, 0x52, 0x79, 0x44, 0x1a, 0xe2, 0x9f, 0x2a, 0x14, 0x5e, 0x48, 0x05, 0x8f, 0x08,
	0x37, 0xbb, 0x85, 0xa8, 0x9d, 0x13, 0x6c, 0x67, 0xc2, 0x9f, 0x83, 0x2f, 0xc6, 0x0b, 0xdf, 0x07,
	0xe5, 0xc6, 0x69, 0x9d, 0x32, 0x90, 0x98, 0x78, 0xcb, 0xb9, 0xe7, 0x5c, 0xfb, 0xfa, 0xdc, 0xd3,
	0xc2, 0x69, 0xa1, 0x72, 0x93, 0x9f, 0xad, 0xb3, 0x14, 0xa5, 0xc6, 0xb3, 0x15, 0xda, 0x09, 0x55,
	0xd8, 0xc0, 0x95, 0xc2, 0xb0, 0xad, 0xd0, 0x9f, 0x85, 0xc2, 0x8b, 0x5a, 0x14, 0x7d, 0xef, 0x00,
	0x8b, 0xd1, 0xce, 0x50, 0xa2, 0x12, 0x06, 0x13, 0xfc, 0x52, 0xa2, 0x36, 0x2c, 0x84, 0x03, 0x5d,
	0x88, 0x14, 0x63, 0xb4, 0xbc, 0x33, 0xea, 0x8c, 0x87, 0xc9, 0x06, 0xb3, 0x11, 0x1c, 0xd2, 0xf7,
	0x1c, 0x53, 0x85, 0x86, 0x77, 0x89, 0xf6, 0x4b, 0xec, 0x36, 0xf4, 0xd2, 0xbc, 0x94, 0x86, 0x07,
	0xa3, 0xce, 0xb8, 0x97, 0xd4, 0xa0, 0x3a, 0x33, 0x15, 0x85, 0x48, 0x33, 0x63, 0xf9, 0x3e, 0x11,
	0x1b, 0xcc, 0x4e, 0xa0, 0x8f, 0x5f, 0x8b, 0x4c, 0x59, 0xde, 0x23, 0xc6, 0x21, 0xc6, 0x61, 0xa0,
	0x4d, 0xae, 0xc4, 0x27, 0xe4, 0x7d, 0xba, 0xa7, 0x81, 0x15, 0x53, 0xa8, 0x7c, 0x99, 0xad, 0x91,
	0x0f, 0x6a, 0xc6, 0xc1, 0xe8, 0x3d, 0xdc, 0x6a, 0xbd, 0x48, 0x17, 0xb9, 0xd4, 0xc8, 0x1e, 0x42,
	0x5f, 0x1b, 0x61, 0x4a, 0x4d, 0x0f, 0x3a, 0x9c, 0x1e, 0x4d, 0x9c, 0x21, 0x93, 0x39, 0x95, 0x13,
	0x47, 0x57, 0xb3, 0xc8, 0xf2, 0x72, 0x81, 0x8a, 0x77, 0x47, 0xc1, 0x78, 0x98, 0x38, 0x14, 0x3d,
	0x82, 0xa3, 0x18, 0xed, 0xdb, 0x12, 0x95, 0x6d, 0x6c, 0xda, 0x4a, 0x6b, 0x93, 0x1a, 0xa9, 0x80,
	0xe3, 0xad, 0xf4, 0x6f, 0xef, 0x7f, 0x00, 0xc1, 0x0a, 0x2d, 0xf9, 0x7a, 0x38, 0x65, 0x1b, 0x55,
	0x8c, 0xf6, 0x95, 0x34, 0x99, 0xb1, 0x49, 0x45, 0x47, 0x1f, 0x68, 0x6f, 0xcf, 0x52, 0x93, 0x5d,
	0x79, 0x7b, 0xfb, 0xcd, 0x40, 0xe4, 0x7d, 0x2e, 0x75, 0x79, 0x49, 0xaf, 0xa2, 0x7d, 0x36, 0xb8,
	0xda, 0x16, 0x2d, 0x8f, 0xb6, 0x35, 0x4c, 0x6a, 0x10, 0x5d, 0x91, 0x8b, 0xdb, 0xf3, 0x6f, 0xe0,
	0x62, 0x8a, 0xea, 0xdd, 0xeb, 0x97, 0xee, 0x3e, 0x87, 0xd8, 0x7d, 0x80, 0x14, 0xd5, 0x8b, 0x5c,
	0x1a, 0x74, 0x01, 0x19, 0x26, 0x5e, 0x25, 0xfa, 0xd6, 0x81, 0xff, 0x63, 0xb4, 0xf3, 0x52, 0x17,
	0x28, 0x2f, 0xfe, 0x4d, 0x1e, 0xb7, 0xae, 0x04, 0x2d, 0x57, 0x8e, 0x21, 0x58, 0x08, 0xe9, 0xc2,
	0x58, 0x7d, 0x56, 0x4a, 0x85, 0x42, 0xe7, 0x92, 0x72, 0x38, 0x4c, 0x1c, 0x8a, 0xce, 0xe1, 0xbf,
	0x18, 0xed, 0x9b, 0x4c, 0x1b, 0xcf, 0xe9, 0x7c, 0xb9, 0xd4, 0x68, 0x68, 0x9e, 0x5e, 0xe2, 0xd0,
	0x36, 0xfb, 0x5d, 0x2f, 0xfb, 0xd1, 0x47, 0xca, 0x4e, 0xdd, 0x7f, 0xe3, 0x3c, 0x04, 0x7f, 0xc8,
	0xc3, 0xf4, 0x47, 0x17, 0x82, 0xca, 0x8d, 0x19, 0x1c, 0x34, 0xd1, 0x67, 0x77, 0x7d, 0xf1, 0xce,
	0x4f, 0x3c, 0xbc, 0x77, 0x3d, 0x59, 0x4f, 0x17, 0xed, 0xb1, 0x73, 0xe8, 0x51, 0x80, 0x19, 0xf7,
	0x85, 0x7e, 0xfc, 0xc3, 0x3b, 0xd7, 0x30, 0x9b, 0xfe, 0x19, 0x1c, 0x34, 0xe9, 0x69, 0x0f, 0xb2,
	0x93, 0xd9, 0xf6, 0x20, 0xbb, 0x81, 0x8b, 0xf6, 0xd8, 0x53, 0x18, 0xb8, 0x34, 0xb0, 0xd0, 0x97,
	0xb6, 0x23, 0x12, 0x9e, 0x6c, 0xb8, 0xe7, 0x6b, 0x21, 0x57, 0xde, 0x01, 0x4f, 0x60, 0xbf, 0x72,
	0x9e, 0x9d, 0xfa, 0xdd, 0xde, 0x2e, 0x43, 0xfe, 0x2b, 0xd1, 0x34, 0x2f, 0xfa, 0xf4, 0x3f, 0xf9,
	0xf8, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xc9, 0x94, 0x68, 0x67, 0x05, 0x00, 0x00,
}
