// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/license/key.proto

package license

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 生成的请求
type KeyGenerateRequest struct {
	SpaceKey             string   `protobuf:"bytes,1,opt,name=spaceKey,proto3" json:"spaceKey,omitempty"`
	SpaceSecret          string   `protobuf:"bytes,2,opt,name=spaceSecret,proto3" json:"spaceSecret,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Capacity             int32    `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Expiry               int32    `protobuf:"varint,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Storage              string   `protobuf:"bytes,6,opt,name=storage,proto3" json:"storage,omitempty"`
	Profile              string   `protobuf:"bytes,7,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyGenerateRequest) Reset()         { *m = KeyGenerateRequest{} }
func (m *KeyGenerateRequest) String() string { return proto.CompactTextString(m) }
func (*KeyGenerateRequest) ProtoMessage()    {}
func (*KeyGenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{0}
}

func (m *KeyGenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyGenerateRequest.Unmarshal(m, b)
}
func (m *KeyGenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyGenerateRequest.Marshal(b, m, deterministic)
}
func (m *KeyGenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyGenerateRequest.Merge(m, src)
}
func (m *KeyGenerateRequest) XXX_Size() int {
	return xxx_messageInfo_KeyGenerateRequest.Size(m)
}
func (m *KeyGenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyGenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyGenerateRequest proto.InternalMessageInfo

func (m *KeyGenerateRequest) GetSpaceKey() string {
	if m != nil {
		return m.SpaceKey
	}
	return ""
}

func (m *KeyGenerateRequest) GetSpaceSecret() string {
	if m != nil {
		return m.SpaceSecret
	}
	return ""
}

func (m *KeyGenerateRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *KeyGenerateRequest) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *KeyGenerateRequest) GetExpiry() int32 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *KeyGenerateRequest) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *KeyGenerateRequest) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

// 生成的回复
type KeyGenerateResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Number               []string `protobuf:"bytes,2,rep,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyGenerateResponse) Reset()         { *m = KeyGenerateResponse{} }
func (m *KeyGenerateResponse) String() string { return proto.CompactTextString(m) }
func (*KeyGenerateResponse) ProtoMessage()    {}
func (*KeyGenerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{1}
}

func (m *KeyGenerateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyGenerateResponse.Unmarshal(m, b)
}
func (m *KeyGenerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyGenerateResponse.Marshal(b, m, deterministic)
}
func (m *KeyGenerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyGenerateResponse.Merge(m, src)
}
func (m *KeyGenerateResponse) XXX_Size() int {
	return xxx_messageInfo_KeyGenerateResponse.Size(m)
}
func (m *KeyGenerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyGenerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyGenerateResponse proto.InternalMessageInfo

func (m *KeyGenerateResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *KeyGenerateResponse) GetNumber() []string {
	if m != nil {
		return m.Number
	}
	return nil
}

// 查询的请求
type KeyQueryRequest struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyQueryRequest) Reset()         { *m = KeyQueryRequest{} }
func (m *KeyQueryRequest) String() string { return proto.CompactTextString(m) }
func (*KeyQueryRequest) ProtoMessage()    {}
func (*KeyQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{2}
}

func (m *KeyQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyQueryRequest.Unmarshal(m, b)
}
func (m *KeyQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyQueryRequest.Marshal(b, m, deterministic)
}
func (m *KeyQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyQueryRequest.Merge(m, src)
}
func (m *KeyQueryRequest) XXX_Size() int {
	return xxx_messageInfo_KeyQueryRequest.Size(m)
}
func (m *KeyQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyQueryRequest proto.InternalMessageInfo

func (m *KeyQueryRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

// 查询的回复
type KeyQueryResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Space                string   `protobuf:"bytes,2,opt,name=space,proto3" json:"space,omitempty"`
	Capacity             int32    `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Expiry               int32    `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Storage              string   `protobuf:"bytes,5,opt,name=storage,proto3" json:"storage,omitempty"`
	Profile              string   `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	ActivatedAt          int64    `protobuf:"varint,9,opt,name=activatedAt,proto3" json:"activatedAt,omitempty"`
	Ban                  int32    `protobuf:"varint,10,opt,name=ban,proto3" json:"ban,omitempty"`
	Active               []string `protobuf:"bytes,11,rep,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyQueryResponse) Reset()         { *m = KeyQueryResponse{} }
func (m *KeyQueryResponse) String() string { return proto.CompactTextString(m) }
func (*KeyQueryResponse) ProtoMessage()    {}
func (*KeyQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{3}
}

func (m *KeyQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyQueryResponse.Unmarshal(m, b)
}
func (m *KeyQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyQueryResponse.Marshal(b, m, deterministic)
}
func (m *KeyQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyQueryResponse.Merge(m, src)
}
func (m *KeyQueryResponse) XXX_Size() int {
	return xxx_messageInfo_KeyQueryResponse.Size(m)
}
func (m *KeyQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyQueryResponse proto.InternalMessageInfo

func (m *KeyQueryResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *KeyQueryResponse) GetSpace() string {
	if m != nil {
		return m.Space
	}
	return ""
}

func (m *KeyQueryResponse) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *KeyQueryResponse) GetExpiry() int32 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *KeyQueryResponse) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *KeyQueryResponse) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *KeyQueryResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *KeyQueryResponse) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *KeyQueryResponse) GetActivatedAt() int64 {
	if m != nil {
		return m.ActivatedAt
	}
	return 0
}

func (m *KeyQueryResponse) GetBan() int32 {
	if m != nil {
		return m.Ban
	}
	return 0
}

func (m *KeyQueryResponse) GetActive() []string {
	if m != nil {
		return m.Active
	}
	return nil
}

// 激活的请求
type KeyActivateRequest struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Consumer             string   `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Space                string   `protobuf:"bytes,3,opt,name=space,proto3" json:"space,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyActivateRequest) Reset()         { *m = KeyActivateRequest{} }
func (m *KeyActivateRequest) String() string { return proto.CompactTextString(m) }
func (*KeyActivateRequest) ProtoMessage()    {}
func (*KeyActivateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{4}
}

func (m *KeyActivateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyActivateRequest.Unmarshal(m, b)
}
func (m *KeyActivateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyActivateRequest.Marshal(b, m, deterministic)
}
func (m *KeyActivateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyActivateRequest.Merge(m, src)
}
func (m *KeyActivateRequest) XXX_Size() int {
	return xxx_messageInfo_KeyActivateRequest.Size(m)
}
func (m *KeyActivateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyActivateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyActivateRequest proto.InternalMessageInfo

func (m *KeyActivateRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *KeyActivateRequest) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *KeyActivateRequest) GetSpace() string {
	if m != nil {
		return m.Space
	}
	return ""
}

// 激活的回复
type KeyActivateResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CerUID               string   `protobuf:"bytes,2,opt,name=cerUID,proto3" json:"cerUID,omitempty"`
	CerContent           string   `protobuf:"bytes,3,opt,name=cerContent,proto3" json:"cerContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyActivateResponse) Reset()         { *m = KeyActivateResponse{} }
func (m *KeyActivateResponse) String() string { return proto.CompactTextString(m) }
func (*KeyActivateResponse) ProtoMessage()    {}
func (*KeyActivateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5dda835d30aee6, []int{5}
}

func (m *KeyActivateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyActivateResponse.Unmarshal(m, b)
}
func (m *KeyActivateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyActivateResponse.Marshal(b, m, deterministic)
}
func (m *KeyActivateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyActivateResponse.Merge(m, src)
}
func (m *KeyActivateResponse) XXX_Size() int {
	return xxx_messageInfo_KeyActivateResponse.Size(m)
}
func (m *KeyActivateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyActivateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyActivateResponse proto.InternalMessageInfo

func (m *KeyActivateResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *KeyActivateResponse) GetCerUID() string {
	if m != nil {
		return m.CerUID
	}
	return ""
}

func (m *KeyActivateResponse) GetCerContent() string {
	if m != nil {
		return m.CerContent
	}
	return ""
}

func init() {
	proto.RegisterType((*KeyGenerateRequest)(nil), "license.KeyGenerateRequest")
	proto.RegisterType((*KeyGenerateResponse)(nil), "license.KeyGenerateResponse")
	proto.RegisterType((*KeyQueryRequest)(nil), "license.KeyQueryRequest")
	proto.RegisterType((*KeyQueryResponse)(nil), "license.KeyQueryResponse")
	proto.RegisterType((*KeyActivateRequest)(nil), "license.KeyActivateRequest")
	proto.RegisterType((*KeyActivateResponse)(nil), "license.KeyActivateResponse")
}

func init() {
	proto.RegisterFile("proto/license/key.proto", fileDescriptor_1b5dda835d30aee6)
}

var fileDescriptor_1b5dda835d30aee6 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x97, 0x66, 0x49, 0x9b, 0xd3, 0x8b, 0x4d, 0x66, 0x02, 0x13, 0x26, 0x54, 0xe5, 0x86,
	0x72, 0xd3, 0x49, 0xe3, 0x1e, 0x69, 0x02, 0xa9, 0x42, 0xbd, 0x22, 0x13, 0x5c, 0x22, 0xb9, 0xee,
	0x01, 0x22, 0xb6, 0x24, 0xd8, 0xce, 0x44, 0x1e, 0x8f, 0x37, 0xe0, 0x8e, 0xd7, 0x41, 0x39, 0x76,
	0xfe, 0x8d, 0x56, 0x88, 0xdd, 0xe5, 0x3b, 0xdf, 0xb1, 0x7d, 0xfc, 0xeb, 0xe7, 0xc2, 0x93, 0x52,
	0x15, 0xa6, 0xb8, 0xb8, 0xc9, 0x24, 0xe6, 0x1a, 0x2f, 0xbe, 0x61, 0xbd, 0xa2, 0x0a, 0x9b, 0xba,
	0x52, 0x1c, 0x8f, 0x3b, 0xf4, 0x57, 0xa1, 0x70, 0x67, 0x9b, 0x92, 0x5f, 0x1e, 0xb0, 0x0d, 0xd6,
	0x6b, 0xcc, 0x51, 0x09, 0x83, 0x29, 0x7e, 0xaf, 0x50, 0x1b, 0x16, 0xc3, 0x4c, 0x97, 0x42, 0xe2,
	0x06, 0x6b, 0xee, 0x2d, 0xbc, 0x65, 0x94, 0x76, 0x9a, 0x2d, 0x60, 0x4e, 0xdf, 0xd7, 0x28, 0x15,
	0x1a, 0x3e, 0x21, 0x7b, 0x58, 0x62, 0x67, 0x10, 0xc8, 0xa2, 0xca, 0x0d, 0xf7, 0x17, 0xde, 0x32,
	0x48, 0xad, 0x68, 0xf6, 0x94, 0xa2, 0x14, 0x32, 0x33, 0x35, 0x3f, 0x26, 0xa3, 0xd3, 0xec, 0x31,
	0x84, 0xf8, 0xa3, 0xcc, 0x54, 0xcd, 0x03, 0x72, 0x9c, 0x62, 0x1c, 0xa6, 0xda, 0x14, 0x4a, 0x7c,
	0x41, 0x1e, 0xd2, 0x39, 0xad, 0x6c, 0x9c, 0x52, 0x15, 0x9f, 0xb3, 0x1b, 0xe4, 0x53, 0xeb, 0x38,
	0x99, 0x7c, 0x84, 0x47, 0xa3, 0x1b, 0xe9, 0xb2, 0xc8, 0x35, 0xb2, 0x17, 0x10, 0x6a, 0x23, 0x4c,
	0xa5, 0xe9, 0x42, 0xf3, 0xcb, 0x93, 0x95, 0x03, 0xb2, 0xba, 0xa6, 0x72, 0xea, 0xec, 0x66, 0x96,
	0xbc, 0xba, 0xdd, 0xa2, 0xe2, 0x93, 0x85, 0xbf, 0x8c, 0x52, 0xa7, 0x92, 0x97, 0x70, 0xb2, 0xc1,
	0xfa, 0x7d, 0x85, 0xaa, 0x6e, 0x31, 0xf5, 0xad, 0x16, 0x52, 0xdb, 0xfa, 0x73, 0x02, 0xa7, 0x7d,
	0xef, 0xff, 0x0e, 0x70, 0x06, 0x01, 0xd1, 0x74, 0x68, 0xad, 0x18, 0xe1, 0xf3, 0x0f, 0xe2, 0x3b,
	0x3e, 0x84, 0x2f, 0x38, 0x88, 0x2f, 0x1c, 0xe1, 0x63, 0xe7, 0x10, 0x49, 0x85, 0xc2, 0xe0, 0xee,
	0xca, 0x10, 0x5a, 0x3f, 0xed, 0x0b, 0x8d, 0x5b, 0x95, 0x3b, 0xe7, 0xce, 0xac, 0xdb, 0x15, 0x9a,
	0x68, 0x08, 0x69, 0xb2, 0x3b, 0xe7, 0x47, 0xe4, 0x0f, 0x4b, 0xec, 0x14, 0xfc, 0xad, 0xc8, 0x39,
	0xd0, 0x98, 0xcd, 0x67, 0x33, 0x3b, 0x35, 0x20, 0x9f, 0x5b, 0xdc, 0x56, 0x25, 0x9f, 0x28, 0x98,
	0x57, 0x6e, 0xed, 0x3f, 0x88, 0x13, 0x9d, 0x22, 0xd7, 0xd5, 0x2d, 0xfd, 0x6c, 0x14, 0xd8, 0x56,
	0xf7, 0x3c, 0xfd, 0x01, 0xcf, 0xe4, 0x8e, 0x62, 0xd2, 0xef, 0xff, 0x80, 0x98, 0x48, 0x54, 0x1f,
	0xde, 0xbd, 0x75, 0xe7, 0x39, 0xc5, 0x9e, 0x03, 0x48, 0x54, 0x6f, 0x8a, 0xdc, 0xa0, 0x7b, 0x01,
	0x51, 0x3a, 0xa8, 0x5c, 0xfe, 0xf6, 0xc0, 0x6f, 0x9e, 0xd1, 0x1a, 0x66, 0x6d, 0x46, 0xd9, 0xb3,
	0xee, 0x90, 0xbf, 0xdf, 0x62, 0x7c, 0xbe, 0xdf, 0xb4, 0xf3, 0x26, 0x47, 0xec, 0x35, 0x04, 0x14,
	0x34, 0xc6, 0x87, 0x8d, 0xc3, 0x9c, 0xc6, 0x4f, 0xf7, 0x38, 0xdd, 0xfa, 0x35, 0xcc, 0x5a, 0x0a,
	0xe3, 0x41, 0xee, 0xb1, 0x1f, 0x0f, 0x72, 0x1f, 0x5c, 0x72, 0xb4, 0x0d, 0xe9, 0x2f, 0xe5, 0xd5,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x51, 0xb2, 0xdb, 0x92, 0x04, 0x00, 0x00,
}
