// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/license/shared.proto

package license

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 状态
type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f71ef6d47559577, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 空白回复
type BlankResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlankResponse) Reset()         { *m = BlankResponse{} }
func (m *BlankResponse) String() string { return proto.CompactTextString(m) }
func (*BlankResponse) ProtoMessage()    {}
func (*BlankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f71ef6d47559577, []int{1}
}

func (m *BlankResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlankResponse.Unmarshal(m, b)
}
func (m *BlankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlankResponse.Marshal(b, m, deterministic)
}
func (m *BlankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlankResponse.Merge(m, src)
}
func (m *BlankResponse) XXX_Size() int {
	return xxx_messageInfo_BlankResponse.Size(m)
}
func (m *BlankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlankResponse proto.InternalMessageInfo

func (m *BlankResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// 空间
type SpaceEntity struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SpaceKey             string   `protobuf:"bytes,2,opt,name=spaceKey,proto3" json:"spaceKey,omitempty"`
	SpaceSecret          string   `protobuf:"bytes,3,opt,name=spaceSecret,proto3" json:"spaceSecret,omitempty"`
	PublicKey            string   `protobuf:"bytes,4,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	PrivateKey           string   `protobuf:"bytes,5,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	Profile              string   `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpaceEntity) Reset()         { *m = SpaceEntity{} }
func (m *SpaceEntity) String() string { return proto.CompactTextString(m) }
func (*SpaceEntity) ProtoMessage()    {}
func (*SpaceEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f71ef6d47559577, []int{2}
}

func (m *SpaceEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceEntity.Unmarshal(m, b)
}
func (m *SpaceEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceEntity.Marshal(b, m, deterministic)
}
func (m *SpaceEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceEntity.Merge(m, src)
}
func (m *SpaceEntity) XXX_Size() int {
	return xxx_messageInfo_SpaceEntity.Size(m)
}
func (m *SpaceEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceEntity.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceEntity proto.InternalMessageInfo

func (m *SpaceEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SpaceEntity) GetSpaceKey() string {
	if m != nil {
		return m.SpaceKey
	}
	return ""
}

func (m *SpaceEntity) GetSpaceSecret() string {
	if m != nil {
		return m.SpaceSecret
	}
	return ""
}

func (m *SpaceEntity) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *SpaceEntity) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *SpaceEntity) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *SpaceEntity) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *SpaceEntity) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// 激活码
type KeyEntity struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Space                string   `protobuf:"bytes,2,opt,name=space,proto3" json:"space,omitempty"`
	Capacity             int32    `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Expiry               int32    `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Storage              string   `protobuf:"bytes,5,opt,name=storage,proto3" json:"storage,omitempty"`
	Profile              string   `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	ActivatedAt          int64    `protobuf:"varint,9,opt,name=activatedAt,proto3" json:"activatedAt,omitempty"`
	Ban                  int32    `protobuf:"varint,10,opt,name=ban,proto3" json:"ban,omitempty"`
	Consumer             []string `protobuf:"bytes,11,rep,name=consumer,proto3" json:"consumer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyEntity) Reset()         { *m = KeyEntity{} }
func (m *KeyEntity) String() string { return proto.CompactTextString(m) }
func (*KeyEntity) ProtoMessage()    {}
func (*KeyEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f71ef6d47559577, []int{3}
}

func (m *KeyEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyEntity.Unmarshal(m, b)
}
func (m *KeyEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyEntity.Marshal(b, m, deterministic)
}
func (m *KeyEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyEntity.Merge(m, src)
}
func (m *KeyEntity) XXX_Size() int {
	return xxx_messageInfo_KeyEntity.Size(m)
}
func (m *KeyEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyEntity.DiscardUnknown(m)
}

var xxx_messageInfo_KeyEntity proto.InternalMessageInfo

func (m *KeyEntity) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *KeyEntity) GetSpace() string {
	if m != nil {
		return m.Space
	}
	return ""
}

func (m *KeyEntity) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *KeyEntity) GetExpiry() int32 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *KeyEntity) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *KeyEntity) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *KeyEntity) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *KeyEntity) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *KeyEntity) GetActivatedAt() int64 {
	if m != nil {
		return m.ActivatedAt
	}
	return 0
}

func (m *KeyEntity) GetBan() int32 {
	if m != nil {
		return m.Ban
	}
	return 0
}

func (m *KeyEntity) GetConsumer() []string {
	if m != nil {
		return m.Consumer
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "license.Status")
	proto.RegisterType((*BlankResponse)(nil), "license.BlankResponse")
	proto.RegisterType((*SpaceEntity)(nil), "license.SpaceEntity")
	proto.RegisterType((*KeyEntity)(nil), "license.KeyEntity")
}

func init() {
	proto.RegisterFile("proto/license/shared.proto", fileDescriptor_2f71ef6d47559577)
}

var fileDescriptor_2f71ef6d47559577 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xcd, 0x8a, 0xdb, 0x30,
	0x14, 0x85, 0x71, 0x1c, 0x3b, 0xf1, 0x35, 0xa5, 0x45, 0x94, 0x22, 0x42, 0x29, 0xc6, 0x9b, 0x66,
	0x95, 0x40, 0x0b, 0xa5, 0xdb, 0x16, 0xba, 0xca, 0x4e, 0x79, 0x02, 0x59, 0xbe, 0x6d, 0xcd, 0xd8,
	0xb2, 0x90, 0xe4, 0x61, 0xfc, 0x50, 0xf3, 0x74, 0xf3, 0x02, 0x83, 0xae, 0x95, 0x9f, 0x17, 0x98,
	0xdd, 0x3d, 0xe7, 0xd8, 0xe7, 0xfa, 0x93, 0x0c, 0x3b, 0x63, 0x47, 0x3f, 0x1e, 0xfb, 0x4e, 0xa1,
	0x76, 0x78, 0x74, 0xff, 0xa5, 0xc5, 0xf6, 0x40, 0x26, 0xdb, 0x44, 0xb7, 0xfe, 0x01, 0xf9, 0xd9,
	0x4b, 0x3f, 0x39, 0xc6, 0x60, 0xad, 0xc6, 0x16, 0x79, 0x52, 0x25, 0xfb, 0x4c, 0xd0, 0xcc, 0x38,
	0x6c, 0x06, 0x74, 0x4e, 0xfe, 0x43, 0xbe, 0xaa, 0x92, 0x7d, 0x21, 0x2e, 0xb2, 0xfe, 0x09, 0xef,
	0x7e, 0xf7, 0x52, 0x3f, 0x08, 0x74, 0x66, 0xd4, 0x0e, 0xd9, 0x57, 0xc8, 0x1d, 0x15, 0x51, 0x41,
	0xf9, 0xed, 0xfd, 0x21, 0xae, 0x38, 0x2c, 0xfd, 0x22, 0xc6, 0xf5, 0x4b, 0x02, 0xe5, 0xd9, 0x48,
	0x85, 0x7f, 0xb4, 0xef, 0xfc, 0x1c, 0xf6, 0x6a, 0x39, 0x2c, 0x7b, 0x0b, 0x41, 0x33, 0xdb, 0xc1,
	0xd6, 0x85, 0x47, 0x4e, 0x38, 0xc7, 0xc5, 0x57, 0xcd, 0x2a, 0x28, 0x69, 0x3e, 0xa3, 0xb2, 0xe8,
	0x79, 0x4a, 0xf1, 0xbd, 0xc5, 0x3e, 0x43, 0x61, 0xa6, 0xa6, 0xef, 0x54, 0x78, 0x7d, 0x4d, 0xf9,
	0xcd, 0x60, 0x5f, 0x00, 0x8c, 0xed, 0x1e, 0xa5, 0xa7, 0xf6, 0x8c, 0xe2, 0x3b, 0x27, 0x30, 0x1b,
	0x3b, 0xfe, 0xed, 0x7a, 0xe4, 0xf9, 0xc2, 0x1c, 0x65, 0xe8, 0x55, 0x16, 0xa5, 0xc7, 0xf6, 0x97,
	0xe7, 0x9b, 0x2a, 0xd9, 0xa7, 0xe2, 0x66, 0x84, 0x74, 0x32, 0x6d, 0x4c, 0xb7, 0x4b, 0x7a, 0x35,
	0xea, 0xe7, 0x15, 0x14, 0x27, 0x9c, 0x23, 0xf3, 0x27, 0xc8, 0xf5, 0x34, 0x34, 0x68, 0x23, 0x75,
	0x54, 0xec, 0x23, 0x64, 0x04, 0x12, 0xa1, 0x17, 0x11, 0x4e, 0x43, 0x49, 0x23, 0x55, 0xe7, 0x67,
	0xc2, 0xcd, 0xc4, 0x55, 0x87, 0x26, 0x7c, 0x32, 0x9d, 0x5d, 0x40, 0x33, 0x11, 0x55, 0xa0, 0x70,
	0x7e, 0xb4, 0xe1, 0xe6, 0x16, 0xc4, 0x8b, 0x7c, 0x1b, 0xbe, 0x70, 0x2b, 0x52, 0x79, 0x3a, 0xc4,
	0x90, 0x17, 0x94, 0xdf, 0x5b, 0xec, 0x03, 0xa4, 0x8d, 0xd4, 0x1c, 0xe8, 0x33, 0xc3, 0x48, 0x5c,
	0xa3, 0x76, 0xd3, 0x80, 0x96, 0x97, 0x55, 0x1a, 0x6e, 0xf9, 0xa2, 0x9b, 0x9c, 0xfe, 0xd3, 0xef,
	0xaf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x81, 0xd9, 0x1a, 0xda, 0xc5, 0x02, 0x00, 0x00,
}
