// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/license/shared.proto

package license

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 状态
type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f71ef6d47559577, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 空白回复
type BlankResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlankResponse) Reset()         { *m = BlankResponse{} }
func (m *BlankResponse) String() string { return proto.CompactTextString(m) }
func (*BlankResponse) ProtoMessage()    {}
func (*BlankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f71ef6d47559577, []int{1}
}

func (m *BlankResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlankResponse.Unmarshal(m, b)
}
func (m *BlankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlankResponse.Marshal(b, m, deterministic)
}
func (m *BlankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlankResponse.Merge(m, src)
}
func (m *BlankResponse) XXX_Size() int {
	return xxx_messageInfo_BlankResponse.Size(m)
}
func (m *BlankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlankResponse proto.InternalMessageInfo

func (m *BlankResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "license.Status")
	proto.RegisterType((*BlankResponse)(nil), "license.BlankResponse")
}

func init() {
	proto.RegisterFile("proto/license/shared.proto", fileDescriptor_2f71ef6d47559577)
}

var fileDescriptor_2f71ef6d47559577 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xc9, 0x4c, 0x4e, 0xcd, 0x2b, 0x4e, 0xd5, 0x2f, 0xce, 0x48, 0x2c, 0x4a, 0x4d,
	0xd1, 0x03, 0x0b, 0x0a, 0xb1, 0x43, 0x45, 0x95, 0xcc, 0xb8, 0xd8, 0x82, 0x4b, 0x12, 0x4b, 0x4a,
	0x8b, 0x85, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83,
	0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0xc9, 0x82, 0x8b, 0xd7, 0x29, 0x27, 0x31, 0x2f, 0x3b, 0x28,
	0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x9d, 0x8b, 0xad, 0x18, 0x6c, 0x10, 0xd8, 0x00,
	0x6e, 0x23, 0x7e, 0x3d, 0xa8, 0x15, 0x7a, 0x10, 0xf3, 0x83, 0xa0, 0xd2, 0x49, 0x6c, 0x60, 0x17,
	0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x65, 0xef, 0xe3, 0xbc, 0x9f, 0x00, 0x00, 0x00,
}
