// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.15.7
// source: proto/license/shared.proto

package license

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 状态
type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 状态信息
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_license_shared_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_license_shared_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_license_shared_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 空白回复
type BlankResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
}

func (x *BlankResponse) Reset() {
	*x = BlankResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_license_shared_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlankResponse) ProtoMessage() {}

func (x *BlankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_license_shared_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlankResponse.ProtoReflect.Descriptor instead.
func (*BlankResponse) Descriptor() ([]byte, []int) {
	return file_proto_license_shared_proto_rawDescGZIP(), []int{1}
}

func (x *BlankResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// 空间
type SpaceEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // 空间名
	SpaceKey    string `protobuf:"bytes,2,opt,name=spaceKey,proto3" json:"spaceKey,omitempty"`       // 空间识别码
	SpaceSecret string `protobuf:"bytes,3,opt,name=spaceSecret,proto3" json:"spaceSecret,omitempty"` // 空间密钥
	PublicKey   string `protobuf:"bytes,4,opt,name=publicKey,proto3" json:"publicKey,omitempty"`     // 公钥
	PrivateKey  string `protobuf:"bytes,5,opt,name=privateKey,proto3" json:"privateKey,omitempty"`   // 私钥
	Profile     string `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`         // 简介
	CreatedAt   int64  `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`    // 创建时间
	UpdatedAt   int64  `protobuf:"varint,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`    // 更新时间
}

func (x *SpaceEntity) Reset() {
	*x = SpaceEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_license_shared_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceEntity) ProtoMessage() {}

func (x *SpaceEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_license_shared_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceEntity.ProtoReflect.Descriptor instead.
func (*SpaceEntity) Descriptor() ([]byte, []int) {
	return file_proto_license_shared_proto_rawDescGZIP(), []int{2}
}

func (x *SpaceEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpaceEntity) GetSpaceKey() string {
	if x != nil {
		return x.SpaceKey
	}
	return ""
}

func (x *SpaceEntity) GetSpaceSecret() string {
	if x != nil {
		return x.SpaceSecret
	}
	return ""
}

func (x *SpaceEntity) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SpaceEntity) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SpaceEntity) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *SpaceEntity) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SpaceEntity) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 激活码
type KeyEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number      string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`            // 序列号
	Space       string   `protobuf:"bytes,2,opt,name=space,proto3" json:"space,omitempty"`              // 空间
	Capacity    int32    `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`       // 可激活的设备数量
	Expiry      int32    `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`           // 有效期，以天为单位，默认为0（永久）
	Storage     string   `protobuf:"bytes,5,opt,name=storage,proto3" json:"storage,omitempty"`          // 自定义数据
	Profile     string   `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`          // 激活码简介
	CreatedAt   int64    `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`     // 创建时间
	UpdatedAt   int64    `protobuf:"varint,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`     // 更改时间
	ActivatedAt int64    `protobuf:"varint,9,opt,name=activatedAt,proto3" json:"activatedAt,omitempty"` // 激活时间
	Ban         int32    `protobuf:"varint,10,opt,name=ban,proto3" json:"ban,omitempty"`                // 禁用状态
	Consumer    []string `protobuf:"bytes,11,rep,name=consumer,proto3" json:"consumer,omitempty"`       // 消费者
}

func (x *KeyEntity) Reset() {
	*x = KeyEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_license_shared_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEntity) ProtoMessage() {}

func (x *KeyEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_license_shared_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEntity.ProtoReflect.Descriptor instead.
func (*KeyEntity) Descriptor() ([]byte, []int) {
	return file_proto_license_shared_proto_rawDescGZIP(), []int{3}
}

func (x *KeyEntity) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *KeyEntity) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *KeyEntity) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *KeyEntity) GetExpiry() int32 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *KeyEntity) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *KeyEntity) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *KeyEntity) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *KeyEntity) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *KeyEntity) GetActivatedAt() int64 {
	if x != nil {
		return x.ActivatedAt
	}
	return 0
}

func (x *KeyEntity) GetBan() int32 {
	if x != nil {
		return x.Ban
	}
	return 0
}

func (x *KeyEntity) GetConsumer() []string {
	if x != nil {
		return x.Consumer
	}
	return nil
}

// 证书
type CertificateEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`              // ID
	Space     string `protobuf:"bytes,2,opt,name=space,proto3" json:"space,omitempty"`          // 空间名
	Number    string `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`        // 激活码
	Consumer  string `protobuf:"bytes,4,opt,name=consumer,proto3" json:"consumer,omitempty"`    // 消费者
	Content   string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`      // 内容
	CreatedAt int64  `protobuf:"varint,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"` // 生成时间
}

func (x *CertificateEntity) Reset() {
	*x = CertificateEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_license_shared_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CertificateEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateEntity) ProtoMessage() {}

func (x *CertificateEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_license_shared_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateEntity.ProtoReflect.Descriptor instead.
func (*CertificateEntity) Descriptor() ([]byte, []int) {
	return file_proto_license_shared_proto_rawDescGZIP(), []int{4}
}

func (x *CertificateEntity) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CertificateEntity) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *CertificateEntity) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CertificateEntity) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *CertificateEntity) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CertificateEntity) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_proto_license_shared_proto protoreflect.FileDescriptor

var file_proto_license_shared_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x2f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x30, 0x0a, 0x0d, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xf3, 0x01, 0x0a, 0x0b, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xad, 0x02, 0x0a,
	0x09, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x62, 0x61, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x62, 0x61, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x22, 0xa7, 0x01, 0x0a,
	0x11, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x17, 0x5a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x3b, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_license_shared_proto_rawDescOnce sync.Once
	file_proto_license_shared_proto_rawDescData = file_proto_license_shared_proto_rawDesc
)

func file_proto_license_shared_proto_rawDescGZIP() []byte {
	file_proto_license_shared_proto_rawDescOnce.Do(func() {
		file_proto_license_shared_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_license_shared_proto_rawDescData)
	})
	return file_proto_license_shared_proto_rawDescData
}

var file_proto_license_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_license_shared_proto_goTypes = []interface{}{
	(*Status)(nil),            // 0: Status
	(*BlankResponse)(nil),     // 1: BlankResponse
	(*SpaceEntity)(nil),       // 2: SpaceEntity
	(*KeyEntity)(nil),         // 3: KeyEntity
	(*CertificateEntity)(nil), // 4: CertificateEntity
}
var file_proto_license_shared_proto_depIdxs = []int32{
	0, // 0: BlankResponse.status:type_name -> Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_license_shared_proto_init() }
func file_proto_license_shared_proto_init() {
	if File_proto_license_shared_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_license_shared_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_license_shared_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlankResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_license_shared_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_license_shared_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_license_shared_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CertificateEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_license_shared_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_license_shared_proto_goTypes,
		DependencyIndexes: file_proto_license_shared_proto_depIdxs,
		MessageInfos:      file_proto_license_shared_proto_msgTypes,
	}.Build()
	File_proto_license_shared_proto = out.File
	file_proto_license_shared_proto_rawDesc = nil
	file_proto_license_shared_proto_goTypes = nil
	file_proto_license_shared_proto_depIdxs = nil
}
