// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/license/space.proto

package license

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Space service

func NewSpaceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Space service

type SpaceService interface {
	// 创建
	Create(ctx context.Context, in *SpaceCreateRequest, opts ...client.CallOption) (*BlankResponse, error)
	// 查询
	Query(ctx context.Context, in *SpaceQueryRequest, opts ...client.CallOption) (*SpaceQueryResponse, error)
	// 列举
	List(ctx context.Context, in *SpaceListRequest, opts ...client.CallOption) (*SpaceListResponse, error)
}

type spaceService struct {
	c    client.Client
	name string
}

func NewSpaceService(name string, c client.Client) SpaceService {
	return &spaceService{
		c:    c,
		name: name,
	}
}

func (c *spaceService) Create(ctx context.Context, in *SpaceCreateRequest, opts ...client.CallOption) (*BlankResponse, error) {
	req := c.c.NewRequest(c.name, "Space.Create", in)
	out := new(BlankResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceService) Query(ctx context.Context, in *SpaceQueryRequest, opts ...client.CallOption) (*SpaceQueryResponse, error) {
	req := c.c.NewRequest(c.name, "Space.Query", in)
	out := new(SpaceQueryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceService) List(ctx context.Context, in *SpaceListRequest, opts ...client.CallOption) (*SpaceListResponse, error) {
	req := c.c.NewRequest(c.name, "Space.List", in)
	out := new(SpaceListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Space service

type SpaceHandler interface {
	// 创建
	Create(context.Context, *SpaceCreateRequest, *BlankResponse) error
	// 查询
	Query(context.Context, *SpaceQueryRequest, *SpaceQueryResponse) error
	// 列举
	List(context.Context, *SpaceListRequest, *SpaceListResponse) error
}

func RegisterSpaceHandler(s server.Server, hdlr SpaceHandler, opts ...server.HandlerOption) error {
	type space interface {
		Create(ctx context.Context, in *SpaceCreateRequest, out *BlankResponse) error
		Query(ctx context.Context, in *SpaceQueryRequest, out *SpaceQueryResponse) error
		List(ctx context.Context, in *SpaceListRequest, out *SpaceListResponse) error
	}
	type Space struct {
		space
	}
	h := &spaceHandler{hdlr}
	return s.Handle(s.NewHandler(&Space{h}, opts...))
}

type spaceHandler struct {
	SpaceHandler
}

func (h *spaceHandler) Create(ctx context.Context, in *SpaceCreateRequest, out *BlankResponse) error {
	return h.SpaceHandler.Create(ctx, in, out)
}

func (h *spaceHandler) Query(ctx context.Context, in *SpaceQueryRequest, out *SpaceQueryResponse) error {
	return h.SpaceHandler.Query(ctx, in, out)
}

func (h *spaceHandler) List(ctx context.Context, in *SpaceListRequest, out *SpaceListResponse) error {
	return h.SpaceHandler.List(ctx, in, out)
}
