// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/license/space.proto

package license

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 创建的请求
type SpaceCreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpaceCreateRequest) Reset()         { *m = SpaceCreateRequest{} }
func (m *SpaceCreateRequest) String() string { return proto.CompactTextString(m) }
func (*SpaceCreateRequest) ProtoMessage()    {}
func (*SpaceCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5687777d02e295a5, []int{0}
}

func (m *SpaceCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceCreateRequest.Unmarshal(m, b)
}
func (m *SpaceCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceCreateRequest.Marshal(b, m, deterministic)
}
func (m *SpaceCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceCreateRequest.Merge(m, src)
}
func (m *SpaceCreateRequest) XXX_Size() int {
	return xxx_messageInfo_SpaceCreateRequest.Size(m)
}
func (m *SpaceCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceCreateRequest proto.InternalMessageInfo

func (m *SpaceCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 查询的请求
type SpaceQueryRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpaceQueryRequest) Reset()         { *m = SpaceQueryRequest{} }
func (m *SpaceQueryRequest) String() string { return proto.CompactTextString(m) }
func (*SpaceQueryRequest) ProtoMessage()    {}
func (*SpaceQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5687777d02e295a5, []int{1}
}

func (m *SpaceQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceQueryRequest.Unmarshal(m, b)
}
func (m *SpaceQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceQueryRequest.Marshal(b, m, deterministic)
}
func (m *SpaceQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceQueryRequest.Merge(m, src)
}
func (m *SpaceQueryRequest) XXX_Size() int {
	return xxx_messageInfo_SpaceQueryRequest.Size(m)
}
func (m *SpaceQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceQueryRequest proto.InternalMessageInfo

func (m *SpaceQueryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 查询的回复
type SpaceQueryResponse struct {
	Status               *Status      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Space                *SpaceEntity `protobuf:"bytes,2,opt,name=space,proto3" json:"space,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SpaceQueryResponse) Reset()         { *m = SpaceQueryResponse{} }
func (m *SpaceQueryResponse) String() string { return proto.CompactTextString(m) }
func (*SpaceQueryResponse) ProtoMessage()    {}
func (*SpaceQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5687777d02e295a5, []int{2}
}

func (m *SpaceQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceQueryResponse.Unmarshal(m, b)
}
func (m *SpaceQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceQueryResponse.Marshal(b, m, deterministic)
}
func (m *SpaceQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceQueryResponse.Merge(m, src)
}
func (m *SpaceQueryResponse) XXX_Size() int {
	return xxx_messageInfo_SpaceQueryResponse.Size(m)
}
func (m *SpaceQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceQueryResponse proto.InternalMessageInfo

func (m *SpaceQueryResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SpaceQueryResponse) GetSpace() *SpaceEntity {
	if m != nil {
		return m.Space
	}
	return nil
}

// 列举的请求
type SpaceListRequest struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpaceListRequest) Reset()         { *m = SpaceListRequest{} }
func (m *SpaceListRequest) String() string { return proto.CompactTextString(m) }
func (*SpaceListRequest) ProtoMessage()    {}
func (*SpaceListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5687777d02e295a5, []int{3}
}

func (m *SpaceListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceListRequest.Unmarshal(m, b)
}
func (m *SpaceListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceListRequest.Marshal(b, m, deterministic)
}
func (m *SpaceListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceListRequest.Merge(m, src)
}
func (m *SpaceListRequest) XXX_Size() int {
	return xxx_messageInfo_SpaceListRequest.Size(m)
}
func (m *SpaceListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceListRequest proto.InternalMessageInfo

func (m *SpaceListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SpaceListRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 列举的回复
type SpaceListResponse struct {
	Status               *Status        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Space                []*SpaceEntity `protobuf:"bytes,3,rep,name=space,proto3" json:"space,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SpaceListResponse) Reset()         { *m = SpaceListResponse{} }
func (m *SpaceListResponse) String() string { return proto.CompactTextString(m) }
func (*SpaceListResponse) ProtoMessage()    {}
func (*SpaceListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5687777d02e295a5, []int{4}
}

func (m *SpaceListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceListResponse.Unmarshal(m, b)
}
func (m *SpaceListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceListResponse.Marshal(b, m, deterministic)
}
func (m *SpaceListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceListResponse.Merge(m, src)
}
func (m *SpaceListResponse) XXX_Size() int {
	return xxx_messageInfo_SpaceListResponse.Size(m)
}
func (m *SpaceListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceListResponse proto.InternalMessageInfo

func (m *SpaceListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SpaceListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SpaceListResponse) GetSpace() []*SpaceEntity {
	if m != nil {
		return m.Space
	}
	return nil
}

func init() {
	proto.RegisterType((*SpaceCreateRequest)(nil), "license.SpaceCreateRequest")
	proto.RegisterType((*SpaceQueryRequest)(nil), "license.SpaceQueryRequest")
	proto.RegisterType((*SpaceQueryResponse)(nil), "license.SpaceQueryResponse")
	proto.RegisterType((*SpaceListRequest)(nil), "license.SpaceListRequest")
	proto.RegisterType((*SpaceListResponse)(nil), "license.SpaceListResponse")
}

func init() {
	proto.RegisterFile("proto/license/space.proto", fileDescriptor_5687777d02e295a5)
}

var fileDescriptor_5687777d02e295a5 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbd, 0x4e, 0x02, 0x41,
	0x10, 0xc7, 0x45, 0xd8, 0x33, 0x8e, 0x85, 0x3a, 0x21, 0x04, 0x96, 0x86, 0x5c, 0x03, 0xb1, 0x80,
	0x04, 0x1f, 0x00, 0x83, 0xb1, 0xb3, 0x71, 0x79, 0x82, 0x15, 0x87, 0x78, 0x11, 0x6f, 0xf1, 0x76,
	0xae, 0xa0, 0xf1, 0x0d, 0x7d, 0x27, 0xc3, 0xec, 0xf2, 0x71, 0x86, 0x68, 0xec, 0x6e, 0xfe, 0xf3,
	0x9b, 0xff, 0xcd, 0xc7, 0x42, 0x67, 0x55, 0x38, 0x76, 0xa3, 0x65, 0x36, 0xa7, 0xdc, 0xd3, 0xc8,
	0xaf, 0xec, 0x9c, 0x86, 0xa2, 0xe1, 0x59, 0x14, 0xb5, 0xfe, 0xc1, 0xbc, 0xda, 0x82, 0x5e, 0x02,
	0x94, 0x0e, 0x00, 0x67, 0x9b, 0x9a, 0xfb, 0x82, 0x2c, 0x93, 0xa1, 0x8f, 0x92, 0x3c, 0x23, 0x42,
	0x23, 0xb7, 0xef, 0xd4, 0xae, 0xf5, 0x6a, 0x83, 0x73, 0x23, 0xdf, 0x69, 0x1f, 0xae, 0x85, 0x7c,
	0x2a, 0xa9, 0x58, 0xff, 0x06, 0x66, 0xd1, 0x32, 0x82, 0x7e, 0xe5, 0x72, 0x4f, 0xd8, 0x87, 0xc4,
	0xb3, 0xe5, 0xd2, 0x0b, 0x7b, 0x31, 0xbe, 0x1c, 0xc6, 0x7e, 0x86, 0x33, 0x91, 0x4d, 0x4c, 0xe3,
	0x0d, 0x28, 0x99, 0xa2, 0x7d, 0x2a, 0x5c, 0x73, 0xcf, 0x6d, 0xd4, 0x87, 0x9c, 0x33, 0x5e, 0x9b,
	0x80, 0xa4, 0x77, 0x70, 0x25, 0xea, 0x63, 0xe6, 0x79, 0xdb, 0x52, 0x0b, 0x12, 0xb7, 0x58, 0x78,
	0x62, 0xf9, 0x91, 0x32, 0x31, 0xc2, 0x26, 0xa8, 0xb9, 0x2b, 0x73, 0x16, 0x5f, 0x65, 0x42, 0x90,
	0x7e, 0xc6, 0xa9, 0x82, 0xc3, 0x7f, 0x7b, 0x6d, 0x82, 0x62, 0xc7, 0x76, 0x29, 0x9e, 0x75, 0x13,
	0x82, 0xfd, 0x04, 0xf5, 0x5e, 0xfd, 0x8f, 0x09, 0xc6, 0x5f, 0x35, 0x50, 0x22, 0xe3, 0x04, 0x92,
	0x70, 0x04, 0xec, 0x56, 0x0b, 0x2a, 0xa7, 0xd1, 0xad, 0x5d, 0x72, 0xba, 0xb4, 0xf9, 0xdb, 0xb6,
	0xe7, 0xf4, 0x04, 0xa7, 0xa0, 0x64, 0xe5, 0xa8, 0xab, 0xf5, 0x87, 0x07, 0xd3, 0xdd, 0xa3, 0xb9,
	0x9d, 0xc7, 0x04, 0x1a, 0x9b, 0x4d, 0x60, 0xa7, 0x8a, 0x1d, 0xec, 0x57, 0xeb, 0x63, 0xa9, 0xad,
	0xc1, 0x73, 0x22, 0xcf, 0xea, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x10, 0xf9, 0x31, 0x69, 0x98,
	0x02, 0x00, 0x00,
}
